version: 0.2

# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

env:
  shell: /bin/sh
        
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      golang: 1.18
    commands:
      - aws --version
      - npm --version
      - go version
      - docker --version
      # docker compose is not supported yet in codebuild standard image: https://github.com/aws/aws-codebuild-docker-images/issues/527
      # - docker compose --version
      - npm install
  pre_build:
    on-failure: ABORT
    commands:
      - go mod tidy
      # - cd test/dynamodb-local
      # - docker compose pull
      # - cd ../../
  build:
    on-failure: ABORT
    commands:
      - bash ./scripts/aws_codebuild_update.sh
      - bash ./scripts/aws_codebuild_deploy.sh
  post_build:
    on-failure: ABORT
    commands:
      - ls -R deployment
artifacts:
  files:
    - deployment/**/*