name: post-merge
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: read
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  package:
    name: build-and-package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: echo
        run: echo "post merge action" # https://github.com/actions/upload-artifact

